-- Ver todas las relaciones (constraints) de la base de datos
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'gestion_academica' 
AND REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY TABLE_NAME;